version: '3'

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5433:5432" # Puerto predeterminado de PostgreSQL
    environment:
      POSTGRES_USER: ${DB_USER}                # Usuario de PostgreSQL
      POSTGRES_PASSWORD: ${DB_PASSWORD}        # Contraseña del usuario
      POSTGRES_DB: ${DB_NAME}                  # Nombre de la base de datos
    container_name: aqukinstorage_db
    volumes:
      - ./postgres:/var/lib/postgresql/data    # Volumen para persistir los datos